version: "3.9"

services:
  py:
    build:
      context: ./
      dockerfile: Dockerfiles/python.Dockerfile
    ports:
      - "8000:8000"
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./mysite:/code
  database:
    build:
      context: ./
      dockerfile: Dockerfiles/postgres.Dockerfile
    env_file:
      - dbcredentials.env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - django_pg_data:/var/lib/postgresql/data/

volumes:
  django_pg_data
