version: "3.9"

services:
  database:
    build:
      context: ./
      dockerfile: Dockerfiles/postgres.Dockerfile
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
    ports:
      - "5789:5432"
    volumes:
      - django_pg_data:/var/lib/postgresql/data/
  py:
    build:
      context: ./
      dockerfile: Dockerfiles/python.Dockerfile
    restart: always
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
    ports:
      - "8000:8000"
    depends_on:
      - database
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./mysite:/code

volumes:
  django_pg_data:
